### ISSUE TITLE
Don't suggest builtin attributes during completion non-first segment in attribute path

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#10058]
## Environment

* **IntelliJ Rust plugin version:** 0.4.188.5171-223-nightly
* **Rust toolchain version:** 1.66.0 (69f9c33d7 2022-12-12) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.3.1 Ultimate Edition (IU-223.8214.52)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.emulate.terminal

## Problem description
The plugin suggested builtin attributes after `::` in an attribute path

<img width="443" alt="Screenshot 2023-01-30 at 12 11 58" src="https://user-images.githubusercontent.com/2539310/215488179-5b4824eb-a18a-4dd2-b796-0817effee074.png">

## Steps to reproduce
`main.rs`
```rust
#[tokio::t]
fn test() {
    
}
```

`Cargo.toml`
```toml
[package]
name = "rust-project"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version="1.24.2", features=["full"] }
```
