### ISSUE TITLE
Incorrect evaluation of Cargo features in dependency when `package` is the same as actual name

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#10074]
## Environment

* **IntelliJ Rust plugin version:** 0.4.188.5180-231-nightly
* **Rust toolchain version:** 1.69.0-nightly (1e225413a 2023-01-28) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2023.1 EAP (CL-231.6471.1)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description

IntelliJ Rust incorrectly evaluates Cargo feature of the dependency crate when the dependency is specified using a  `package` key with the same name as the actual dependency name. On the screenshot, the feature `my_cool_feature` is shown as disabled, and the code insight works correspondingly.

**`package` with the same name (does not work)**
![rename](https://user-images.githubusercontent.com/4854600/216326062-8e8730f3-4def-4f8a-b3c9-5e80a5bd774b.PNG)

<details>
  <summary>Note, in other cases, it works fine</summary>
  
**No `package` (works fine)** 
![without-rename](https://user-images.githubusercontent.com/4854600/216326064-0f0d7a22-4ff8-428e-a4bf-496714fd167b.PNG)

**`package` with a different name (works fine)**
![actual_rename](https://user-images.githubusercontent.com/4854600/216326057-d7838581-4b51-48e0-9050-647e73123cb8.PNG)

</details>

This is a common practice to explicitly specify the exact package name for the dependency

## Steps to reproduce

`Cargo.toml`
```Toml
[package]
name = "cfg_feature_test"
version = "0.1.0"
edition = "2021"

[dependencies]
my-cool-crate  = { package = "my-cool-crate", path = "my-cool-crate", features = ["my_cool_feature"] }
```

`my-cool-crate/Cargo.toml`
```Toml
[package]
name = "my-cool-crate"
version = "0.1.0"
edition = "2021"

[features]
my_cool_feature = []
```
