### ISSUE TITLE
E0308: expected `Option<Entity>`, found `Vec<<unknown>>`

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#10184]
## Environment

* **IntelliJ Rust plugin version:** 0.4.190.5232-231-nightly
* **Rust toolchain version:** 1.69.0-nightly (7aa413d59 2023-02-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2023.1 EAP (CL-231.7665.29)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.macros.proc

## Problem description
<img width="592" alt="изображение" src="https://user-images.githubusercontent.com/49211026/221625900-e344dc00-277e-4b25-972f-33be8e01f341.png">

```
mismatched types [E0308] expected `Option<Entity>`, found `Vec<<unknown>>` 
```

## Steps to reproduce
```toml
[dependencies]
serde = { version = "1", features = ["derive"] }
surrealdb = { git = "https://github.com/surrealdb/surrealdb", rev = "5e2236d", default-features = false, features = ["kv-mem", "kv-rocksdb"] }
tokio = { version = "1", features = ["full"] }

```

```rust
use serde::{
    Deserialize,
    Serialize,
};
use surrealdb::engine::any::connect;

#[derive(Debug, Serialize, Deserialize)]
struct Entity {
    id: Option<String>,
    field: String,
}

#[tokio::main]
async fn main() {
    let db = connect("mem://").await.unwrap();

    let entity: Option<Entity> = db
        .update(("foo", "first"))
        .content(Entity {
            id: None,
            field: "value".to_string(),
        })
        .await
        .unwrap();

    println!("{entity:?}");
}

```
