### ISSUE TITLE
Typing is really slow and laggy

### ISSUE THREAD

**Issue by aSemy** [intellij-rust/intellij-rust#10832]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.71.0-nightly (4ca000ac8 2023-07-13) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2023.2.1 Ultimate Edition (IU-232.9559.62)
* **Operating system:** Windows 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description

When I type in a `main.rs` file the whole UI freezes and lags. It's even slow when I'm just writing a comment - no Rust code.

When I type in a non-Rust file performance is fine.

I recorded a video of me typing in a .rs and .txt files: https://i.imgur.com/d2G6OnK.mp4

<blockquote class="imgur-embed-pub" lang="en" data-id="a/M5PZ8O4"  ><a href="//imgur.com/a/M5PZ8O4"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

### `src/main.rs`

```rust
#![no_std]
#![no_main]

// extern crate alloc;

use esp_println::println;
use hal::{peripherals::Peripherals, prelude::*, Rtc, Rng};
use hal::clock::ClockControl;
use hal::timer::TimerGroup;

use core::panic::PanicInfo;

// mod wifi;
// mod metrics;

// // If using the `binstart` feature of `esp-idf-sys`, always keep this module imported
// use esp_idf_sys as _;

/// This configuration is picked up at compile time by `build.rs` from the file `cfg.toml`.
#[toml_cfg::toml_config]
pub struct Config {
    #[default("")]
    wifi_ssid: &'static str,
    #[default("")]
    wifi_psk: &'static str,
}


#[entry]
fn main() -> ! {
    let peripherals = Peripherals::take();
    let mut system = peripherals.DPORT.split();
    let clocks = ClockControl::boot_defaults(system.clock_control).freeze();

    // Disable the RTC and TIMG watchdog timers
    let mut rtc = Rtc::new(peripherals.RTC_CNTL);
    let timer_group0 = TimerGroup::new(
        peripherals.TIMG0,
        &clocks,
        &mut system.peripheral_clock_control,
    );
    let mut wdt0 = timer_group0.wdt;
    let timer_group1 = TimerGroup::new(
        peripherals.TIMG1,
        &clocks,
        &mut system.peripheral_clock_control,
    );
    let mut wdt1 = timer_group1.wdt;
    rtc.rwdt.disable();
    wdt0.disable();
    wdt1.disable();
    println!("Hello world!");


    // let metrics = Metrics::new();
    // let mut rng = rand::thread_rng();
    let mut rng = Rng::new(peripherals.RNG);

    loop {
        // IU am trying to type.

        // but it's really lagging.
        Wh
        // rng.
        if rng.gen::<u8>() > 200  {
            // metrics.counter.inc();
            // println!(metrics.counter.get());
        }
    }
}

/// This function is called on panic.
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}
```

### `Cargo.toml`

```toml
[package]
name = "fqnet_rust"
version = "0.1.0"
authors = ["Adam"]
edition = "2021"


[profile.release]
opt-level = "s"
lto = "off"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
lto = "off"

[features]
#default = ["esp32"]
wifi = ["esp-wifi/wifi"]

#default = ["native"]
#native = ["esp-idf-sys/native"]

[dependencies]
hal = { package = "esp32-hal", version = "0.14.0" }
esp-backtrace = { version = "0.7.0", features = ["esp32", "panic-handler", "exception-handler", "print-uart"] }
esp-println = { version = "0.5.0", features = ["esp32"] }

#rustfft = "=6.1.0"
#easyfft = "=0.3.5"

#anyhow = "=1.0.71"

#esp-idf-hal = "=0.41.1"
#esp-idf-svc = { version = "=0.46.0", features = ["experimental", "alloc"] }
#esp-idf-sys = { version = "=0.33.0", features = ["binstart"] }
#log = "=0.4.18"
##rgb-led = { path = "../../common/lib/rgb-led" }
toml-cfg = "=0.1.3"
##wifi = { path = "../../common/lib/wifi" }
#
##embedded-svc = "=0.25.0"
#esp-idf-hal = "=0.41.1"
#esp-idf-svc = { version = "=0.46.0", features = ["experimental", "alloc"] }
#esp-idf-sys = "=0.33.0"
#log = "=0.4.18"

#prometheus = "0.13.3"

[dependencies.esp-wifi]
git = "https://github.com/esp-rs/esp-wifi.git"
rev = "b8bddffa46605a082610e8fc2fea90af98dacb3d"
features = ["esp32", "wifi", "esp-now"]

[profile.dev.package.esp-wifi]
opt-level = 3


[build-dependencies]
anyhow = "=1.0.71"
embuild = "=0.31.2"
toml-cfg = "=0.1.3"
```

### `rust-toolchain.toml`

```toml
[toolchain]
channel = "esp"
components = ["rustfmt", "rustc-dev"]
targets = ["xtensa-esp32-none-elf"]
```
