### ISSUE TITLE
Conditionally disabled code is unexpectedly disabled

### ISSUE THREAD

**Issue by mennanov** [intellij-rust/intellij-rust#10863]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2023.2.1 Ultimate Edition (IU-232.9559.62)
* **Operating system:** macOS 13.5.2
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description

The conditionally disabled code under the feature flag `#[cfg(feature = "dangerous_configuration")]` in `rustls` crate is treated as disabled even then the feature is enabled in `Cargo.toml`.

The code that is expected to be enabled is disabled:

<img width="827" alt="Screenshot 2023-09-13 at 14 00 48" src="https://github.com/intellij-rust/intellij-rust/assets/1451079/18dd1d15-713b-4c12-a163-226cb21e9b77">

When such a code is referenced in the project code Intellij complains with the following error message:
<img width="767" alt="Screenshot 2023-09-13 at 13 47 06" src="https://github.com/intellij-rust/intellij-rust/assets/1451079/80f1c265-e490-47c4-9965-453bc3d4a4f0">

`Cargo.toml`:

```toml
[package]
name = "bftd-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
bollard = { version = "0", features = ["buildkit"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.25", features = ["full"] }
tokio-stream = "*"
tokio-rustls = "0.24.*"
rustls = { package = "rustls", version = "0.21.*", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.*"
rustls-pki-types = "0.2.*"
rustls-webpki = { package = "rustls-webpki", version = "0.101.*", features = ["alloc", "std"] }

[dev-dependencies]
sandbox = { path = "sandbox" }
bollard = { version = "0", features = ["buildkit"] }
hyper = "*"
tar = "0.4.*"
tokio-util = "*"

[workspace]
members = ["sandbox"]
```

Project tree:

```
.
├── Cargo.lock
├── Cargo.toml
├── bftd-server.iml
├── sandbox
│   ├── Cargo.toml
│   └── src
│       ├── bin
│       │   └── main.rs
│       └── lib.rs
├── src
│   ├── bin
│   │   └── main.rs
│   ├── lib.rs
│   └── links.rs
└── tests
    ├── calculator.rs
    ├── common
    │   └── mod.rs
    ├── links.rs
    └── sandbox_launcher
        └── mod.rs
```

## Steps to reproduce

Enable the `dangerous_configuration` feature for the `rustls` crate in `Cargo.toml`. 
Observe that the code under this feature flag is still disabled.
