### ISSUE TITLE
Highlighting and completion break with `p256` crate

### ISSUE THREAD

**Issue by edgarogh** [intellij-rust/intellij-rust#10861]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.72.0 (5680fa18f 2023-08-23) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2023.2.1 (CL-232.9559.58)
* **Operating system:** Linux 5.15.0-83-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description

When referencing some functions from `p256` or `elliptic-curve`, syntax highlighting is frozen and reduced to the bare minimum (only keywords are in a color while the rest is in default color — no underlines for mut, no color for macros, no colors for attributes, etc.). _Go to definition_ is broken, _rename refactoring_ is broken, suggestions don't show, etc. It's as if the whole plugin had stopped working.

## Steps to reproduce

```toml
[package]
name = "intellij-rust-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
elliptic-curve = { version = "0.13.5", features = ["sec1"] }
p256 = { version = "0.13.2", features = ["arithmetic", "ecdsa"] }
```

`src/main.rs`:
```rust
use p256::ecdsa::signature::rand_core::OsRng;
use p256::SecretKey;
use p256::elliptic_curve::sec1::ToEncodedPoint;

fn main() {
    let sk = SecretKey::random(&mut OsRng);
    let pk = sk.public_key();
    pk.to_encoded_point();
}
```

Now try do write stuff at the end of the main function: `dbg!("hello workd")` (no color on `dbg!`), `let mut abc = 1;` (no underline on abc), etc.
