### ISSUE TITLE
TOML plugin: Nested folding

### ISSUE THREAD

**Issue by arperry** [intellij-rust/intellij-rust#10887]
```toml
[foo]
key = "val"

[foo.bar]
key = 123

[foo.bar.baz]
key = 456
```

Code folding right now is on the per-key level. If I fold foo, I'm not getting the subkeys:

```toml
[foo] {...}

[foo.bar]
key = 123

[foo.bar.baz]
key = 456
```

I would prefer that folding work as it does elsewhere. For example, if I fold foo.bar, then foo.bar.baz should be folded:

```toml
[foo]
key = "val"

[foo.bar] {...}
```

TOML doesn't guarantee that the keys will be in order, of course, but when they are, expanding the folding to include subkeys would ease my team's pain points from having migrated from JSON. My co-workers who use Visual Studio assure me that this is the existing behavior over there.
