### ISSUE TITLE
Error when using 0.# in TOML file

### ISSUE THREAD

**Issue by Joshua-F** [intellij-rust/intellij-rust#1441]
I have something defined like below, but the plugin seems to be displaying an error at the period. It only gives this error when starting the double with a 0.

```toml
[[entry]]
item = 1234
amount = 1
chance = 0.5
```

![Error picture](http://i.imgur.com/QA43Noy.png)

Might be somewhat related to intellij-rust/intellij-toml#13

Unrelated, but I also noticed a lack of syntax highlighting, if this is a bug I'll open up a separate issue.
