### ISSUE TITLE
Can't find crate with relative path in workspace

### ISSUE THREAD

**Issue by andy-hanson** [intellij-rust/intellij-rust#1798]
**Cargo.toml**:

```toml
[workspace]
members = [
	"crates/util",
	"crates/main",
]
```

**crates/main/Cargo.toml**:

```toml
[package]
name = "main"
version = "0.1.0"

[dependencies]
util = { path = "../util" }
```

**crates/main/src/main.rs**:

```rust
extern crate util;
use util::add;

fn main() {
	println!("{}", add(1, 2));
}
```

**crates/util/Cargo.toml**:

```toml
[package]
name = "util"
version = "0.1.0"

[dependencies]
```

**crates/util/lib.rs**:

```rust
pub fn add(a: usize, b: usize) -> usize {
	a + b
}
```

Go to `main.rs`. You will see an IDE error at `extern crate util;`: "Can't find crate for `util` [E0463]". But it works with the command-line (`cargo run -p main`).

This *was* working until recently, maybe about a week ago.
