### ISSUE TITLE
No colored output with custom Cargo subcommand alias

### ISSUE THREAD

**Issue by sanmai-NL** [intellij-rust/intellij-rust#1824]
Running `cargo clippy` with `intellij-rust` produces colored terminal output for me under the current nightly of Cargo and `intellij-rust`.

With a custom Cargo subcommand alias, however, ‘Terminal’ output is colored tab within IntelliJ IDEA, but not when invoked as a ‘Run configuration’.

`.cargo/config`:
```toml
[alias]
stress_test = ["clippy", "-v", "--color=always", "--", ...]
```

This results in the command line:
`/usr/bin/rustup run nightly /usr/bin/cargo stress_test` ->
`/usr/bin/rustup run nightly /usr/bin/cargo clippy --color=always -v`

Setting a custom env var `TERM=xterm+256color` within the ‘Run configuration’ does not help.
