### ISSUE TITLE
IntelliJ index operation won't stop

### ISSUE THREAD

**Issue by itmuckel** [intellij-rust/intellij-rust#2323]
I just updated to intellij-rust 0.2.0.2088 and now the indexing operation won't ever finish. 

IntelliJ stops indexing, when I remove the `target` folder, but this is no solution as I need to recompile all libs from scratch. As soon es everything is compiled again, the indexing operation kicks in and never stops. Anyone else experiencing this?

I use Windows 10, but I think I witnessed the same problem on my other machine running Ubuntu.

(Downgrading to the previous version fixes this for me temporarily.)

**Comment by vlad20012** [comment]
itmuckel can you please spcify the rust project in which this bug is reproduced (if it is open-source, of course)? Or the project does not matter?

**Comment by itmuckel** [comment]
You're right, I tried a different project and there it worked fine. 

The problematic project is a game I write, but I cannot release the source right now, because I don't own the rights for all the assets I use. Here are the contents of my cargo.toml (without the package section):
```toml
[profile.dev]
opt-level = 2

[dependencies.ggez]
version = "0.4.0"
features = ["cargo-resource-root"]

[dependencies]
specs = "0.10"
specs-derive = "0.1"
palette = "0.2"
rand = "0.3"
time = "0.1"
```
