### ISSUE TITLE
Incorrect error on procedural macros with colons (`::`) in their names

### ISSUE THREAD

**Issue by konstin** [intellij-rust/intellij-rust#2362]
When a procedural macro has a `::` in its name, a syntax error is shown even thought the code is prefectly valid rust.

Example:

```rust
#![feature(proc_macro, specialization)]

extern crate pyo3;

use pyo3::prelude::*;

#[py::class]
struct MyClass {
    num: i32,
    debug: bool,
    token: PyToken,
}
```

Cargo.toml:

```toml
[package]
authors = ["konstin"]
name = "mylib"
version = "0.1.0"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.2.5"
features = ["extension-module"]
```

The following incorrect error is shown in line 7: `'!' expected, got '::'`
