### ISSUE TITLE
Cannot resolve symbols anymore if cargo-features=["rename-dependency"] is used

### ISSUE THREAD

**Issue by aldanor** [intellij-rust/intellij-rust#3044]
Now that rename-dependency has been stabilized and uplifted into beta, it would be nice if it was supported.

`Cargo.toml`:

```toml
cargo-features = ["rename-dependency"]

[dependencies]
foo = { package = "bar", version = "0.1" }
```

Somewhere in the codebase...

```rust
use foo::Foo;  // <-- can no longer resolve it, any uses of Foo are highlighted red
```

(Versions: default toolchain is nightly via rustup; latest nightly compiler build; latest IntelliJ Rust plugin version)
