### ISSUE TITLE
Stderr is not a tty, which means color-backtrace disables coloring

### ISSUE THREAD

**Issue by ArekPiekarz** [intellij-rust/intellij-rust#4061]
## Environment

* **Intellij-Rust plugin version:** 0.2.100.2128-191
* **Rust toolchain version:** 1.35.0
* **IDE name and version:** IntelliJ IDEA 2019.1.3 (Community Edition)
* **Operating system:** Xubuntu 19.04

## Problem description
I originally opened an issue for the [color-backtrace](https://crates.io/crates/color-backtrace) crate - https://github.com/athre0z/color-backtrace/issues/14. Since its version 0.2.0 it didn't print colored output in IntelliJ with Rust plugin when your program panicked. The reason for it is color-backtrace now checks if stderr is a TTY and disables colors if not, as if writing to a file.

I was advised to ask here if the Rust plugin or IntelliJ IDEA could have a setting to emulate the terminal when providing the stderr to `cargo run` command or similar, allegedly similarly to Pycharm?

## Steps to reproduce

1. Create new Rust project, using these files:
src/main.rs:
```rust
fn main() {
    color_backtrace::install();
    panic!("I'm panicking");
}
```
Cargo.toml
```toml
[package]
name = "color-backtrace-test"
version = "0.1.0"
authors = ["John Smith"]
edition = "2018"

[dependencies]
#color-backtrace = "0.1.3" # works
color-backtrace = "0.2.1" # doesn't work
```
2. On the right click "Add configuration".
3. In the dialog on the left click "+" -> Cargo Command
4. The "Command" field should say "run", click Ok.
5. Run the newly added command by the "Run" button.
