### ISSUE TITLE
can not debug unittests in proc macro crate

### ISSUE THREAD

**Issue by reuvenpo** [intellij-rust/intellij-rust#4299]
## Environment

* **IntelliJ Rust plugin version:** v0.2.103.2131-191
* **Rust toolchain version:** 1.37
* **IDE name and version:** Clion 2019.1.4 / 2019.2
* **Operating system:** Pop!_OS 2018.04 (basically Ubuntu)

## Problem description
When trying to debug unittests (test module with `#[test]` functions inside proc macro crates, the debugger fails with "Test framework quit unexpectedly"

In the debug menu i can see that GDB is failing with the following message:
```
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/reuven/projects/test-macro/target/debug/test_macro-4e617a3dab30b553.
Use `info auto-load python-scripts [REGEXP]' to list them.
[Inferior 1 (process 31636) exited with code 0177]
```

## Steps to reproduce
1. create a proc-macro crate with a no-op implementation of the macro (or no macro at all)
2. write a test module with a single test function
3. try to debug it

example code:
```toml
# Cargo.toml
[package]
name = "test-macro"
version = "0.1.0"
authors = ["whatever"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
```
```rust
// lib.rs
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);  // breakpoint here, and try to use the gutter button to debug
    }
}
```
