### ISSUE TITLE
Some types do not autocomplete when autocomplete otherwise works

### ISSUE THREAD

**Issue by jen20** [intellij-rust/intellij-rust#4421]
## Environment

* **IntelliJ Rust plugin version:** 0.2.105.2133-192
* **Rust toolchain version:** 1.39.0-nightly (eceec57f7 2019-09-18)
* **IDE name and version:** CLion 2019.2.2 Build #CL-192.6603.37
* **Operating system:** Windows or MacOS X

## Problem description

The use of certain crates fails to provide autocompletion or inline type annotation hints for some of their types. Autocomplete works with some other types in those crates, and with those from other crates and the standard library.

## Steps to reproduce

`Cargo.toml`:

```toml
[package]
name = "threading-spike4"
version = "0.1.0"
authors = ["Test"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.5"
```

`main.rs`:

```rust
use tokio::runtime::Builder;

fn main() {
    // "Builder" provides no completion options for most functions, and no type hint is displayed
    let runtime = Builder::new().build().unwrap();
    runtime.block_on(async {});
}
```

As can be seen in the following screenshot, there is also no type annotation hints on the `runtime` variable.

![image](https://user-images.githubusercontent.com/548524/65389301-bd9dd000-dd4c-11e9-8b51-885ee503aec2.png)
