### ISSUE TITLE
Enhance Cargo.toml `dependencies` section completion

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#4455]
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2134-193
* **Rust toolchain version:** 1.37.0 (eae3437df 2019-08-13) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3 EAP (CL-193.3519.24)
* **Operating system:** macOS 10.14.6

## Problem description

Cargo.toml `dependencies` section (and similar `*-dependencies` sections either) can get a better completion for the following cases:

- [x] Better handling of `{`
```toml
[dependencies]
lazy_static = <CARET>"1.1.0"
```

If I place `{` symbol where the <CARET> is, I currently get the following text:
```toml
[dependencies]
lazy_static = {<CARET>}"1.1.0"
```

instead, it would be great to have the following:
```toml
[dependencies]
lazy_static = {version = "1.1.0"<CARET>}
```

- [x] It would be great to have the completion for all possible fields for dependency: `version`, `default-features`, `features`, `path` etc. for cases like

```toml
[dependencies]
lazy_static = {version = "1.1.0"<CARET>}
```

Currently there are no options given.

- [x] When editing the path for a dependency

```toml
[dependencies]
data = { path = "../data<CARET>" }
```

I would like to have a completion based on the directory structure.
Currently there are no options given.

- [x] Provide completion options for features

```toml
[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"<CARET>] }
```

Currently there are no options given.
