### ISSUE TITLE
`use crate_name::crate_name` breaks resolution

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#4509]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2135-193 (previous also tested, I think)
* **Rust toolchain version:** 1.38.0
* **IDE name and version:** IntelliJ IDEA Ultimate 2019.3 193.4099.13 EAP (2019.2.3 also tested)
* **Operating system:** Windows 10 x64

## Problem description
If a user imports a macro (or possibly anything) named the same name as the crate containing it, then navigation/resolution break for that crate. For example:

* `use anyhow::anyhow;`
* `use lazy_static::lazy_static;`

## Steps to reproduce

Cargo.toml:
```toml
[package]
name = "anyhow-test"
version = "0.1.0"
authors = ["Alyosha Vasilieva <1284317+AlyoshaVasilieva@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.8"
```

main.rs (working version):
```rust
use anyhow::{Error, ensure};

fn main() -> Result<(), Error>{
    println!("Hello, world!");
    Ok(())
}
```

Everything is normal in the working version. (There is a compile warning about `ensure` not being used, of course)

main.rs (broken version):
```rust
use anyhow::{Error, anyhow};

fn main() -> Result<(), Error>{
    println!("Hello, world!");
    Ok(())
}
```

In the broken version:
* Ctrl-clicking the use statements gives "Cannot find declaration to go to"
* The `Error` usage is red and reads "Unresolved reference: Error"

However, compilation works fine (again with a warning about unused import).

Auto-completion is broken by this. If you have `use anyhow::{Error, anyh};` then IntelliJ will happily autocomplete the "anyhow" on request and then die and stop giving any autocomplete suggestions for `anyhow`.
