### ISSUE TITLE
Inference broken for &[u8].splitn().next()

### ISSUE THREAD

**Issue by jcdyer** [intellij-rust/intellij-rust#4585]
## Environment

* **IntelliJ Rust plugin version:** 0.2.108.2148-192
* **Rust toolchain version:** 1.38.0 (625451e37 2019-09-23) x86_64-unknown-linux-gnu
* **IDE name and version:** GoLand 2019.2.3 (GO-192.6817.25)
* **Operating system:** Linux 5.3.7-zen1-1-zen

## Problem description

Inference is broken for `[u8].splitn().next()`.

## Steps to reproduce

Create a project with the following files:

Cargo.toml

```toml
[package]
name = "splitner"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
```

lib.rs:

```rust
fn splitter(s: &[u8]) -> Option<&[u8]> {
    let mut splits = s.splitn(2, |x| *x == 0);
     splits.next()
}
```
`splits.next()` renders a red squiggly error:

```
mismatched types [E0308] 
expected `Option<&[u8]>`, found `Option<&SplitN<u8, fn(&u8) -> bool>>` 
```

The code compiles just fine from the command line, and tests (not shown above) pass.

Note, the problem goes away with any of the following changes:
* Change the serde dependency to `serde = "1"` (without the derive feature).
* Remove the serde dependency
* Change the types in the function signature from &[u8] to &str
* Change `s.splitn(2, ...)` to `s.split(...)`
