### ISSUE TITLE
Unresolved references and no type inference with uom crate

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#4945]
## Environment

* **IntelliJ Rust plugin version:** 0.2.116.2847-193-nightly
* **Rust toolchain version:** 1.41 stable
* **IDE name and version:** IntelliJ IDEA 2019.3.2 Ultimate
* **Operating system:** Windows 10 x64

## Problem description
[uom](https://github.com/iliekturtles/uom) crate has no type inference, unresolved reference errors, and navigation doesn't work.

## Steps to reproduce

Cargo.toml:

```toml
[package]
name = "bug-repro"
version = "0.1.0"
authors = ["Malloc Voidstar <1284317+AlyoshaVasilieva@users.noreply.github.com>"]
edition = "2018"

[dependencies]
uom = "=0.26.0"
```

main.rs:

```rust
use uom::si::f32::*;
use uom::si::length::kilometer;
use uom::si::time::second;

fn main() {
    let length = Length::new::<kilometer>(5.0);
    let time = Time::new::<second>(15.0);
    let velocity = length / time;
    let _acceleration = calc_acceleration(velocity, time);
}

fn calc_acceleration(velocity: Velocity, time: Time) -> Acceleration {
    velocity / time
}
```

`Velocity`, `Time`, and `Acceleration` for `calc_acceleration` are marked red with "Unresolved reference".

No type inference on `length`, `time`, or `velocity` variables.

No navigation/doc popup for `Length`, `Time`, or their `new` functions in `main`. Also no navigation/autocomplete for the type aliases such as `uom::si::f32`

Compilation works with no errors.

Experimental macro expansion engine is enabled, as well as `org.rust.cargo.evaluate.build.scripts`. This plugin version is the first nightly with #4914.
