### ISSUE TITLE
compare Cargo.toml fields, not the content to reduce rust macro expend

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#5062]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.3007-193-nightly
* **Rust toolchain version:** rustc 1.43.0-nightly (823ff8cf1 2020-03-07)
* **IDE name and version:** clion 2019.3.4
* **Operating system:** Arch Linux

## Problem description

With enable the new macro expansion system, I notice when I modify `Cargo.toml`, the macro expansion system will re-parse rust macro. However, If I just add a new line into the end of `Cargo.toml`, it will re-parse too. Is there a way to compare `Cargo.toml` fileds, not the content, to reduce macro re-parse

## Steps to reproduce

- enable the new macro expansion system

- write a `Cargo.toml`
```toml
[package]
name = "test"
version = "0.1.0"
authors = ["Sherlock Holo <xx@xx.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
```

- waiting parse done.

- add a new line into `Cargo.toml`

rust macro will be re-parse
