### ISSUE TITLE
False-positive compile error from non-imported traits from other workspace dependencies

### ISSUE THREAD

**Issue by aloucks** [intellij-rust/intellij-rust#5132]
## Environment

* **IntelliJ Rust plugin version:** Rust (0.2.118.2171-193)
* **Rust toolchain version:** rustc 1.42.0 (b8cedc004 2020-03-09)
* **IDE name and version:**  IntelliJ IDEA 2019.3.4 Build #IC-193.6911.18 March 17, 2020
* **Operating system:** Windows 10 amd64

## Problem description
False positive compile errors are displayed on trait implementations from non-imported traits (that happen to exist in dependencies from other workspace crates).

![image](https://user-images.githubusercontent.com/221559/77494605-881d9080-6e1c-11ea-8d02-549b5a4ecfa6.png)

![image](https://user-images.githubusercontent.com/221559/77495008-c2d3f880-6e1d-11ea-9ce6-9cad22560f7b.png)

## Steps to reproduce

`workspace/Cargo.toml`
```toml
[workspace]
members = ["liba", "libb"]
```

`workspace/liba/Cargo.toml`
```toml
[package]
name = "liba"
version = "0.1.0"
edition = "2018"

[dependencies]
# standback = "0.2.0"
# the time crate pulls in "standback"
time = "0.2.9"
```

`workspace/libb/Cargo.toml`
```toml
[package]
name = "libb"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1.0"
```

`workspace/libb/src/lib.rs`
```rust
bitflags::bitflags! {
    pub struct FooFlags: u32 {
        const A = 1;
        const B = 2;
    }
}

pub fn foo() {
    let a = FooFlags::A;
    if a.contains(FooFlags::B) {   // <-- false positive compile error here
        println!("B");
    }
}
```

The `contains` function is generated from`bitflags` and is valid, but somehow IntelliJ is picking up a trait impl from the the `standback` crate which is **not** imported in the file nor is it even a dependency of the crate. It **is** however, a transitive dependency from the `time` crate in a _different workspace member_.  

If I comment out the `time` crate in the other `liba/Cargo.toml` the compile error goes away after the macro expansion refreshes. 
 
This only started happening recently after the last update.
