### ISSUE TITLE
Procedural macros shadow traits

### ISSUE THREAD

**Issue by netvl** [intellij-rust/intellij-rust#5158]
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.2158-201
* **Rust toolchain version:** rustc 1.42.0 (b8cedc004 2020-03-09)
* **IDE name and version:** IntelliJ IDEA 2020.1 EAP (Ultimate Edition), Build #IU-201.6487.11, built on March 17, 2020
* **Operating system:** Windows 10

## Problem description

Imported procedural macros shadow traits, resulting in "unresolved reference" errors.

Many procedural macros, e.g. `thiserror::Error` or `derive_more::{From, Error, Display}` have to be imported in a way which shadows builtin traits. For example:

```rust
use derive_more::From;

#[derive(From)]
struct Something {
    ...
}
```

Note that the original trait still can be used just fine, for example:

```rust
use derive_more::From;

#[derive(From)]
struct Something {
    ...
}

let some_var: Something = From::from(...);
```

IDEA, however, highlights `From` in the `From::from` invocation as `unresolved reference: 'From'`.

## Steps to reproduce

```toml
# Cargo.toml

[package]
name = "from-example"
version = "0.1.0"
authors = ["Vladimir Matveev <vmatveev@citrine.cc>"]
edition = "2018"

[dependencies]
derive_more = "0.99.5"
```

```rust
// src/main.rs

use derive_more::From;

#[derive(From, Debug)]
struct SomeStruct {
    inner: i32
}

fn main() {
    let s: SomeStruct = From::from(123);
    println!("Result: {:?}", s);
}
```
![image](https://user-images.githubusercontent.com/280456/78002031-6d9b5980-72eb-11ea-871f-123cbe0d4c92.png)

The code compiles just fine and prints `Result: SomeStruct { inner: 123 }` as expected.
