### ISSUE TITLE
Type inference is inaccurate for CRATE MIO poll with cfg_os_poll! macro

### ISSUE THREAD

**Issue by zhouanqidelaoba** [intellij-rust/intellij-rust#5263]
## Environment

* **IntelliJ Rust plugin version:** 0.2.120.2202-201
* **Rust toolchain version:** 1.41.0 stable
* **IDE name and version:** CLion 2020.1
* **Operating system:** Mac catalina

## Problem description
code with crate mio.
the "poll" will not infer struct `Poll`, with macro cfg_os_poll! is set in Cargo.toml

## Steps to reproduce

```rust
let mut poll = Poll::new()?;
```

```toml
[dependencies]
mio = { version = "0.7.0", features = ["os-poll"] }
```
