### ISSUE TITLE
False positive E0603

### ISSUE THREAD

**Issue by fabianvdW** [intellij-rust/intellij-rust#5407]
## Environment
* **IntelliJ Rust plugin version:**: 0.2.122.3105-193
* **Rust toolchain version:**:cargo 1.43.0 (2cbe9048e 2020-05-03), stable-x86_64-pc-windows-gnu (default), rustc 1.43.1 (8d69840ab 2020-05-04)
* **IDE name and version:** IntelliJ IDEA 2019.1.3
* **Operating system:** Windows7

## Problem description
IntelliJ gives a false positive private import error.

## Steps to reproduce
```rust
use tokio::time::timeout;
```
`Cargo.toml`:
```toml
[dependencies.tokio]
version = "0.2.19"
features = ["process", "rt-core", "io-util", "time", "stream", "rt-threaded"]
```
```
Module `tokio::time::timeout` is private [E0603]
```
