### ISSUE TITLE
Implement initial formatter for toml lang

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5518]
## Environment

* **IntelliJ Toml plugin version:** 0.2.124.168-193-nightly
* **IDE name and version:** IntelliJ IDEA 2020.2 EAP Ultimate Edition (IU-202.5103.13)
* **Operating system:** macOS 10.13.6

## Problem description
Currently, toml plugin doesn't provide any formatting.
Unfortunately, I don't know if the official formatting for language exists. But we can start at least with spacing between tokens. All examples from the official [repo](https://github.com/toml-lang/toml) contain spaces before/after `=`, after `,`, before/after `}`, `]`, `{` and `[` in objects and arrays, no spaces in dotted keys, etc. 

## Steps to reproduce
```toml
foo="bar"
object={a=1,b=2}
array=[1,2,3]
key1 . key2='value'
[ key . "key2" . key3 ]
```
