### ISSUE TITLE
False positive mismatched types (E0308) for cgmath/mint::Point2

### ISSUE THREAD

**Issue by ozkriff** [intellij-rust/intellij-rust#5936]
## Environment

* **IntelliJ Rust plugin version:** 0.3.128.3278-202
* **Rust toolchain version:** 1.45.2
* **IDE name and version:** CLion 2020.2
* **Operating system:** Kubuntu 19.10

## Problem description

![image](https://user-images.githubusercontent.com/662976/90316981-e3b4fb80-df2e-11ea-9f70-4acb62d03b24.png)

## Steps to reproduce

`Cargo.toml`:

```toml
[package]
name = "ijrust_cgmath_point_repr"
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = { version = "0.17", features = ["mint"] }
mint = "0.5"

```

`src/main.rs`:

```rust
fn get_mint_point() -> mint::Point2<f32> { [0.0, 0.0].into() }
fn do_stuff(_cg_point: cgmath::Point2<f32>) {}

fn main() {
    // let cg_point: cgmath::Point2<f32> = mint_point.into(); // works fine
    let cg_point = get_mint_point().into(); // causes: mismatched types [E0308] expected `Point2<f32>`, found `[f32; 2]`
    do_stuff(cg_point);
}
```
