### ISSUE TITLE
Target's required-features should be automatically passed to a run configuration

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#6262]
Consider `Cargo.toml`:
```toml
[package]
name = "example_project"
version = "0.1.0"
authors = []
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"
required-features = ["foo"]

[features]
baz = []
```
and `src/main.rs`:
```
fn main() { println!("Hello, World!") }
```

Then, if I run this `main`, the plugin creates a cargo run configuration with a command `run --package example_project --bin main` that fails with this error:

```
> cargo build --color=always --package example_project --bin main --message-format=json
error: target `main` in package `example_project` requires the features: `baz`
Consider enabling them by passing, e.g., `--features="baz"`
```

The plugin should automatically add this `--features="baz"` to a run configuration using `CargoWorkspace.Target.requiredFeatures`.
