### ISSUE TITLE
Can't Go To Declaration for crates which export a different crate name than their crates.io name

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#647]
In `Cargo.toml`:

```toml
[package]
name = "rust_test"
version = "0.1.0"
authors = [""]

[dependencies]
piston2d-graphics = "0.17.0"
```

In `main.rs`:
```rust
extern crate graphics;

use graphics::*;  // Cannot Go To Declaration (Ctrl-Click)

fn main() {
}
```

This seems to be because `piston2d-graphics` != `graphics`?  Not sure how difficult that is to solve.
