### ISSUE TITLE
External libraries list can display a branch name instead of a crate name

### ISSUE THREAD

**Issue by kumbayo** [intellij-rust/intellij-rust#658]
When cargo libraries are specified using a git branch instead of a crate name/version
the project tree shows the branch name of this crate instead of showing the crate name/version.
![intellij_external_libraries_shows_branch_name](https://cloud.githubusercontent.com/assets/1041267/18326421/f228bf00-7545-11e6-86fb-b4bd7bc67af8.png)

Example Cargo.toml

``` toml
[package]
name = "test_external_libraries"
version = "0.1.0"
authors = ["Example <example@example.com>"]

[dependencies]

[dependencies.qmlrs]
git = "https://github.com/flanfly/qmlrs"

[dependencies.graph_algos]
git = "https://github.com/flanfly/rust-graph-algos.git"
```

Normally the last component of the library path contains the crate name + version.
For git libraries the last component of the library path is the branch name (most times master).

I tried analysing this but I only came as far as finding some classes/methods which are probably involved.

```
CargoProjectWorkspaceImpl.updateModuleDependencies()
ModuleUtil Module.updateLibrary()
PsiJavaDirectoryImpl.getPresentation()
PsiDirectoryNode.updateImpl()
PresentationData.setPresentableText()
AbstractPsiBasedNode.update()
```
