### ISSUE TITLE
Feature toggles being duplicated when writing invalid dotted keys in features table

### ISSUE THREAD

**Issue by avrong** [intellij-rust/intellij-rust#6742]
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.SNAPSHOT-203-dev
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** macOS 10.15.7
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

<img width="300" src="https://user-images.githubusercontent.com/6342851/106034075-7fa08100-60e3-11eb-9b3b-c90bc8344280.png">

## Steps to reproduce

1. Start with regular valid features
   ```toml
   [features]
   a = []
   b = []
   ```
2. Make their keys dotted
   ```toml
   [features]
   a.a.b.d = []
   b.c = []
   ```
