### ISSUE TITLE
False positive Use of moved value

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6826]
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3661-203-nightly
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.3.2 Ultimate Edition (IU-203.7148.57)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

![image](https://user-images.githubusercontent.com/2539310/107560797-dc755e80-6bee-11eb-828f-8fedb0fa2cf9.png)

## Steps to reproduce
`src/main.rs`
```rust
use serde_json::Value;
use std::convert::TryFrom;
use std::borrow::Cow;
use serde::{Serialize,Deserialize};

#[derive(Debug,Clone,Serialize,Deserialize,Eq,PartialEq)]
struct OcppCall {
    message_id: String,
    action: String,
    payload: Value,
}

impl TryFrom<Value> for OcppCall {
    type Error = ();

    fn try_from(value: Value) -> Result<Self, ()> {
        let mut items : [Value; 4] = serde_json::from_value(value.clone()).unwrap();

        if let [
        Value::Number(n),
        Value::String(message_id), // warning
        Value::String(action), // warning
        payload @ Value::Object(_)
        ] = items {
            Ok(Self {
                message_id,
                action,
                payload
            })
        } else {
            Err(())
        }
    }
}

fn main() {}
```

`Cargo.toml`
```toml

[package]
name = "rust_project"
version = "0.1.0"
authors = []
edition = "2018"


[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
```
