### ISSUE TITLE
Derive proc macro is not resolved with `extern crate` and `macro_use`

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7061]
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.SNAPSHOT-211-dev
* **Rust toolchain version:** 1.53.0-nightly (07e0e2ec2 2021-03-24) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1 Ultimate Edition (IU-211.6693.103)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I just tried to reproduce #1786 with #6992 but found that if I use original instruction from https://docs.rs/derive_builder/0.10.0/derive_builder/ (i.e. with `extern crate` and `macro_use`), `Builder` cannot be resolved and as a result, macro expansion cannot work.
I suppose it's important because it prevents proper custom derive macro support even there is a workaround

## Steps to reproduce
`Cargo.toml`
```toml
[package]
name = "rust_project"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
derive_builder = "0.10.0"
```

`src/main.rs`
```rust
#[macro_use]
extern crate derive_builder;

#[derive(Clone, Debug, Builder)] // `Builder` cannot be resolved
pub struct MyStruct {
    foo: String
}

fn main() {}
```
