### ISSUE TITLE
Derive proc macro is not suggested in completion

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7062]
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.SNAPSHOT-211-dev
* **Rust toolchain version:** 1.51.0 (2fd73fabe 2021-03-23) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1 Ultimate Edition (IU-211.6693.103)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Related to #7061

When I try to use `Builder` custom derive macro from `derive_builder` lib, `Builder` is not suggested by the plugin in use item.

![image](https://user-images.githubusercontent.com/2539310/113837661-bc998b80-9796-11eb-9204-df76ddee3891.png)

Note, it's successfully resolved if I write complete use item: `use derive_builder::Builder;`

## Steps to reproduce
`Cargo.toml`
```toml
[package]
name = "rust_project"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
derive_builder = "0.10.0"
```

`src/main.rs`
```rust
use derive_builder::/*caret*/;

#[derive(Clone, Debug, Builder)]
pub struct MyStruct {
    foo: String
}

fn main() {}
```
