### ISSUE TITLE
Syntax highlighting and autocompletion don't work inside macro (like async_stream, lazy_static and etc)

### ISSUE THREAD

**Issue by BratSinot** [intellij-rust/intellij-rust#7242]
## Environment

* **IntelliJ Rust plugin version:** 0.4.147.3871-211
* **Rust toolchain version:** nightly-x86_64-pc-windows-msvc
* **IDE name and version:** Clion 2021.1.1
* **Operating system:** Windows 10

## Problem description
Syntax highlighting and autocompletion not work inside macros.

## Steps to reproduce
```toml
[package]
name = "main"
version = "0.1.0"
authors = ["bratsinot"]
edition = "2018"

[dependencies]
async-stream = "0.3.1"
lazy_static = "1.4.0"
```
```rust
fn main() {
    async_stream::stream! {
        qwe
        println!("{}", asd);
    }

    lazy_static::lazy_static! {
        qwe
        println!("{}", asd);
    }
}
```
![image](https://user-images.githubusercontent.com/3810015/119123977-d508f100-ba38-11eb-8fe5-d317c2a9e321.png)
![image](https://user-images.githubusercontent.com/3810015/119123978-d508f100-ba38-11eb-91ab-74dc5e525932.png)
