### ISSUE TITLE
Methods not recognized for implemented generic trait

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#743]
`Cargo.toml`:
```toml
[package]
name = "rust_test"
version = "0.1.0"
authors = ["johnthagen <johnthagen@gmail.com>"]

[dependencies]
piston_window = "0.54.0"
```
`main.rs`:
```rust

extern crate piston_window;

use piston_window::{EventLoop, PistonWindow, WindowSettings};

fn main() {
    let mut window: PistonWindow = WindowSettings::new("Window", [1024, 600])
        .exit_on_esc(true).build().unwrap();

    window.set_ups(60);  // <--- Not recognized as method
    window.set_max_fps(60);  // <--- Not recognized as method
}
```

Documentation for methods:
- [`set_ups`](http://docs.piston.rs/piston_window/event_loop/trait.EventLoop.html#tymethod.set_ups)
- [`set_max_fps`](http://docs.piston.rs/piston_window/event_loop/trait.EventLoop.html#tymethod.set_max_fps)
- [Implementation of `EventLoop` trait](http://docs.piston.rs/piston_window/src/piston_window/src/lib.rs.html#320-338)
