### ISSUE TITLE
Dependency bitvec breaks syntax highlighting / analysis

### ISSUE THREAD

**Issue by notmgsk** [intellij-rust/intellij-rust#7464]
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3968-211
* **Rust toolchain version:** cargo 1.53.0 (4369396ce 2021-04-27)
* **IDE name and version:** 
```
CLion 2021.1.2
Build #CL-211.7442.42, built on June 1, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang (0.2.150.3968-211), org.rust.lang (0.4.150.3968-211), ru.adelf.idea.dotenv (2021.2)
```
* **Operating system:** macos Big Sur

## Problem description

In a simple project, if you include a dependency on `bitvec` it appears to break highlighting and analysis of code that uses the name `Store`.

## Steps to reproduce

1. Code that works as expected:
`Cargo.toml`
```Toml
[package]
name = "test-weird-store"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```
and
`main.rs`
```Rust
enum Hello {
    World(String),
    Store { name: String },
}

fn thing(hi: Hello) {
    match hi {
        Hello::World(_) => {}
        Hello::Store { name } => {
            println!("{}", name);
        }
    }
}

fn main() {
    thing(Hello::World("hi".to_string()));
    println!("Hello, world!");
}
```
This highlights and analyses the `Store` token correctly. See screenshot and note that, in the `match`, the `Hello::Store` arm is highlighted properly, and the `name` field has type `String`:
<img width="1440" alt="Screen Shot 2021-07-06 at 12 24 04 PM" src="https://user-images.githubusercontent.com/16821631/124592927-ec1f6900-de55-11eb-88bf-1b40766b93d7.png">

2. Code the produces the error:
`Cargo.toml`
```Toml
[package]
name = "test-weird-store"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "*"
```
and
`main.rs`
```Rust
enum Hello {
    World(String),
    Store { name: String },
}

fn thing(hi: Hello) {
    match hi {
        Hello::World(_) => {}
        Hello::Store { name } => {
            println!("{}", name);
        }
    }
}

fn main() {
    thing(Hello::World("hi".to_string()));
    println!("Hello, world!");
}
```
This fails to highlight and analyse the `Store` token. See the screenshot and note that the `Store` arm is *not* syntax highlighted and the type of the `name` field is now `unknown`:
<img width="1440" alt="Screen Shot 2021-07-06 at 12 24 19 PM" src="https://user-images.githubusercontent.com/16821631/124593334-6b14a180-de56-11eb-8227-08cb64b49240.png">
