### ISSUE TITLE
Stuck on resolve project depends on stm32f4xx_hal 0.10.0

### ISSUE THREAD

**Issue by tfx2001** [intellij-rust/intellij-rust#7949]
## Environment

* **IntelliJ Rust plugin version:** 0.4.156.4145-212
* **Rust toolchain version:** 1.55.0
* **IDE name and version:** CLion 
* **Operating system:** Windows 10 Home Edition 21H1

## Problem description

When I open the project that depends on `stm32f4xx_hal 0.10.0`，plugin stuck at `Expading Rust macros: Preparing resolve data`

## Steps to reproduce

```toml
[dependencies.stm32f4xx-hal]
version = "0.10.0"
features = ["rt", "stm32f407"]
```
