### ISSUE TITLE
IDE fails to resolve proc-macros

### ISSUE THREAD

**Issue by hamza1311** [intellij-rust/intellij-rust#8178]
## Environment

* **IntelliJ Rust plugin version:** 0.4.161.4266-212-nightly
* **Rust toolchain version:** 1.56.1 (59eed8a2a 2021-11-01) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.2.3 Ultimate Edition (IU-212.5457.46)
* **Operating system:** Linux 5.15.3-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

IDE is unable to detect macro's existence. Jumping to declaration results in the following:

![image](https://user-images.githubusercontent.com/47357913/143458631-e7ace618-8f70-4c5a-abf8-d57337313872.png)

The macro exists and the code compiles.

## Steps to reproduce

**Cargo.toml**
```toml
[package]
name = "irrelevant"
version = "0.1.0"
edition = "2021" # 2018 results in same error

[dependencies]
yew = { git = "https://github.com/yewstack/yew/" }
```

**main.rs**
```rust
fn main() {
    let _ = yew::html! {
        <div>{"This is a test"}</div>
    };
}
```

- Try to use any of the IDE features on the `yew::html!` macro
- Observe how IDE fails to resolve macro
