### ISSUE TITLE
Quick fix to fill parameters of function marked  as #[start]

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8215]
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4280-213-nightly
* **Rust toolchain version:** 1.58.0-nightly (547a6ffee 2021-10-21) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.3 Ultimate Edition (IU-213.5744.223)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

The plugin detects E0132, and it seems helpful to fill parameters of function with a quick fix.
<img width="818" alt="изображение" src="https://user-images.githubusercontent.com/49211026/144388155-85582d18-ce77-4133-aade-8e478313602b.png">

## Steps to reproduce
cargo.toml:
```toml
cargo-features = ["strip"]

[package]
name = "sandbox"
version = "0.1.0"
authors = [""]
edition = "2018"

[profile.dev]
panic = "abort"


[dependencies]
libc = '0.2.108'
```
main.rs:
```rust
#![feature(start)]
#![no_std]

extern crate libc;

#[start]
fn start(_argc: isize, _argv: *const *const u8) -> isize { // remove parameters
    0
}
#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
```
