### ISSUE TITLE
tokio::time::sleep doesn't have postfix .await completion

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#8294]
## Environment

* **IntelliJ Rust plugin version:** 0.4.163.4311-213-nightly
* **Rust toolchain version:** rustc 1.59.0-nightly (c5ecc1570 2021-12-15)
* **IDE name and version:** Clion 2021.3
* **Operating system:** Archlinux

## Problem description
The `tokio::time::sleep` return a Future which can use `.await` directly, but now the IDE doesn't show `.await` completion

![image](https://user-images.githubusercontent.com/10096425/146424124-98a232fa-f47d-4388-a0b4-584b8a83f1b1.png)

## Steps to reproduce
`main.rs`
```rust
use std::time::Duration;

fn main() {
    tokio::time::sleep(Duration::from_secs(1))./*caret*/; // <- invoke completion here
}
```
`Cargo.toml`
```toml
[package]
name = "rust_project"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["time"] }
```
