### ISSUE TITLE
TOML: escaped backslashes at the end of string are treated as unescaped

### ISSUE THREAD

**Issue by Iaiao** [intellij-rust/intellij-rust#8448]
## Environment

* **IntelliJ Toml plugin version:** 213.5744.224

## Problem description

Escaped backslashes at the end of string (`"some string ending with \\"`) are treated as unescaped and escape the `"` character.

## Steps to reproduce

```toml
string = "some string ending with \\" # unmatched `"`, but seems to be fine for some reason
arr = [ "some string ending with \\" ] # unmatched `"`, it treats `" ]` as a part of the string, so `[` is unmatched
```
![image](https://user-images.githubusercontent.com/55715058/150619325-ff540a71-beaa-4e82-88a0-cdad5f738fcf.png)
