### ISSUE TITLE
False Error with strum #[derive(Display)]: enum doesn't implement Display

### ISSUE THREAD

**Issue by pedrofgodinho** [intellij-rust/intellij-rust#8847]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4627-221
* **Rust toolchain version:** 1.60.0
* **IDE name and version:** CLion 2022.1.1
* **Operating system:** Windows 11

## Problem description

After using strum to derive Display causes the IDE to report that enum does not implement the Display trait when trying to print it. 
![image](https://user-images.githubusercontent.com/5845396/168827777-e12ce159-362a-4183-8f2c-49c3a620f36d.png)

## Steps to reproduce

This code compiles and runs correctly, yet reports an error both with and without external linter enabled. 

```toml
[package]
name = "bugexample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24"
strum_macros = "0.24"
```

```rust
use strum_macros::Display;

#[derive(Display)]
enum Example {
    VariantA,
    VariantB
}

fn main() {
    println!("{} {}", Example::VariantA, Example::VariantB);
}
```
