### ISSUE TITLE
Feature request: Import a dependency in Cargo.toml with quick fix on unresolved import.

### ISSUE THREAD

**Issue by Stock84-dev** [intellij-rust/intellij-rust#8879]
A lot of the times I find myself copying code from different crates in a workspace that use same dependencies. I either need to use `cargo add` or open both Cargo.toml to copy the dependency.

For example:
```rust
use async_trait::async_trait;
use workspace_crate::Foo;
```
I could use quick fix to add a dependency in Cargo.toml. It should be able to lookup a crate from crates.io and from a workspace.
After a quick fix:
```toml
[dependencies]
workspace_crate = { path = "../workspace_crate", version = "0.1.0" }
async-trait = "0.1.51"
```
