### ISSUE TITLE
Cargo.toml autocomplete not working

### ISSUE THREAD

**Issue by mylvghb** [intellij-rust/intellij-rust#8883]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4627-221
* **Rust toolchain version:** 1.61.0 (fe5b13d68 2022-05-18) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.1.1 (CL-221.5591.52)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
When I add the `rand` crate, the suggestion list cannot be given：
![image](https://user-images.githubusercontent.com/35945793/170931685-c97a0ea6-0932-44eb-92e1-b9a5d106d5e1.png)

## Steps to reproduce
1. Type the `ran` keyword under the `[dependencies]` section.
2. No suggestion list pops up.

**Comment by neonaot** [comment]
I can't reproduce this problem:
* **IntelliJ Rust plugin version:** 0.4.170.4627-221
* **Rust toolchain version:** 1.62.0-nightly (055bf4ccd 2022-04-25) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.1.1 (CL-221.5591.52)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
<img width="377" alt="image" src="https://user-images.githubusercontent.com/49211026/171158565-f8c8dbf7-2ebc-47b3-a15f-84cec9a537d0.png">

**Comment by mylvghb** [comment]
[idea.log](https://github.com/intellij-rust/intellij-rust/files/8806387/idea.log)
Log file generated by restarting the IDE

**Comment by mylvghb** [comment]
Downloading the creates in the official **crates.io** in China is very slow, so I used a proxy source：
``` TOML
[source.crates-io]
replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true
```
