### ISSUE TITLE
false unused import

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#9179]
## Environment

* **IntelliJ Rust plugin version:** 0.4.177.4803-222-nightly
* **Rust toolchain version:** rustc 1.65.0-nightly (34a6cae28 2022-08-09)
* **IDE name and version:** Clion 2022.2
* **Operating system:** Archlinux

## Problem description
false unused import when use aya_bpf macro mark the function

```rust
#![no_std]
#![no_main]

use core::ffi::{c_int, c_uint};

use aya_bpf::macros::{cgroup_sock_addr, kprobe, sock_ops};
use aya_bpf::programs::{ProbeContext};

#[kprobe(name = "tcp_connect")]
fn tcp_connect(ctx: ProbeContext) {
    todo!()
}
```

intellij-rust will report

> Unused import: `aya_bpf::programs::{ProbeContext}` 

however ProbeContext is used as a argument type

![image](https://user-images.githubusercontent.com/10096425/183864351-726d9c80-d0ea-47c3-a38c-a06e31fdf43b.png)

these features are enabled

**Comment by dima74** [comment]
@Sherlock-Holo could you please provide your dependencies? I can't find `aya_bpf` on crates.io

**Comment by vlad20012** [comment]
It's https://github.com/aya-rs/aya

**Comment by dima74** [comment]
@Sherlock-Holo could you please provide complete code sample? I am not familiar to `aya`, and can't reproduce the problem with just
```toml
[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
```

<img src="https://user-images.githubusercontent.com/6505554/184028588-4f0e04fe-d53c-43dc-9e2c-520a1d81f1cc.png" width="50%">

**Comment by Sherlock-Holo** [comment]
the main.rs

```rust
#![no_std]
#![no_main]

use core::ffi::{c_int, c_uint};

use aya_bpf::macros::{cgroup_sock_addr, kprobe, sock_ops};
use aya_bpf::programs::{ProbeContext, SockAddrContext, SockOpsContext};

#[kprobe(name = "tcp_connect")]
fn tcp_connect(ctx: ProbeContext) {
    todo!()
}
```

the dependencies is 

```toml
[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
```

you should create a file `.cargo/config.toml` in the project root dir, content is 

```toml
[build]
target = "bpfel-unknown-none"

[unstable]
build-std = ["core"]
```

so you can build the bpf target

@dima74
