### ISSUE TITLE
Failed to sync when unknown crate is behind a cfg attribute

### ISSUE THREAD

**Issue by Bben01** [intellij-rust/intellij-rust#9231]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4815-221
* **Rust toolchain version:** 1.63.0
* **IDE name and version:** CLion 2022.1.3
* **Operating system:** Windows, but rust installed in wsl 

## Problem description
If I have the following `Cargo.toml`, it should succeed syncing the project, but instead it fails

## Steps to reproduce
 - `cargo new`
 - add this to your `Cargo.toml`:
```toml
[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
tokio = "2"  # crate that doesn't exist
```
 - sync the project
 
The sync should succeed because the unknown dependency is behind a `cfg` attribute, so it shouldn't take it into account when fetching crates.
