### ISSUE TITLE
Incorrect doc link for derive macros

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#9353]
## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4874-222-nightly
* **Rust toolchain version:** 1.63.0 (4b91a6ea7 2022-08-08) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.2 (CL-222.4167.25)
* **Operating system:** Linux 5.4.0-125-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

The quick doc link generator doesn't recognize derive macros, instead treating them as ordinary functions and producing wrong links. It also mangles capitalization of identifiers, at least in that case.

## Steps to reproduce

```toml
# Cargo.toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"
[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
```

```rust
// main.rs
use clap::Parser;

#[derive(/*caret*/Parser)]
struct Args {}

fn main() {}
```

Open Quick Documentation. At the bottom click on `'parser' on docs.rs`. The opened link is https://docs.rs/clap_derive/3.2.18/clap_derive/fn.parser.html , which doesn't have the doc page. The correct link should be https://docs.rs/clap_derive/3.2.18/clap_derive/derive.Parser.html . Note `derive` instead of `fn` and capitalization of `Parser`.
