### ISSUE TITLE
Add support for workspace key inheritance in Cargo.toml

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#9456]
Rust 1.64 has added support for workspace-level [[package]](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) and [[dependencies]](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace) tables. Keys can be defined at the workspace level in the virtual manifest, and inherited in the crates using the `key.workspace = true` syntax. There are some intentions and inspections which would help to deal with workspace-level keys.

In the following, we consider a single crate inside of a workspace with the following virtual manifest:
```toml
[workspace]
members = ["bar"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
cc = "1.0"
serde = { version = "1.0", features = ["derive"], default-features = false }
rand = "0.8.5"

[workspace.dependencies.regex]
version = "1.6.0"
default-features = false
features = ["std"]
```

Workspace crate, with inherited fields:
```toml
[project]
name = "bar"
version = "0.2.0"
edition.workspace = true

[dependencies]
regex = { workspace = true, features = ["unicode"] }

[dependencies.serde]
workspace = true
features = ["std"]

[build-dependencies]
cc.workspace = true

[dev-dependencies]
rand = { workspace = true, optional = true }
```

Workspace crate, with all inherited fields inlined:
```toml
[project]
name = "bar"
version = "0.2.0"
edition = "2021"

[dependencies]
regex = { version = "1.6.0", default-features = false, features = ["std", "unicode"] }

[dependencies.serde]
version = "1.0" 
features = ["derive", "std"]
default-features = false

[build-dependencies]
cc = "1.0"

[dev-dependencies]
rand = { version = "0.8.5", optional = true }
```

- [ ] Add intention "inline inherited value" to convert inherited keys to their values. 
- [ ] Add inlay hints to show the current value of workspace-inherited keys. 
- [ ] Add inspection to detect keys which can be inherited from the workspace.
- [ ] Add intention to inherit keys from the workspace. It should work like the inverse of the "inline inherited value" intention above.
- [ ] Add inspection which marks `optional` key in `[workspace.dependencies]` fields as an error, with a fix to remove `optional`.
- [ ] Add navigation between workspace keys and their inheriting fields. I.e. `key.workspace` should resolve to the workspace key declaration in the virtual manifest, and `Find usages` on the workspace key `[workspace.package.key]` or `[workspace.dependencies.key]` should find all instances of `key.workspace`.
