### ISSUE TITLE
Macro expansion in wrong working directory

### ISSUE THREAD

**Issue by DzenanJupic** [intellij-rust/intellij-rust#9481]
## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4887-222-beta
* **Rust toolchain version:** 1.66.0-nightly (01af5040f 2022-10-04) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.3 (CL-222.4167.35)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

If a proc macro in a workspace is executed, the macro expansion code and `rustc` use different working directories for executing the macro in. `rustc` executes the macro in the workspace root, while the proc macro expansion code seems to execute it in the package root of the calling `crate`.

This leads to expansion not working correctly if the macro accesses files using a relative path.

## Steps to reproduce

```toml
# ./Cargo.toml
[workspace]
members = ["caller", "macros"]
```

```toml
# ./macros/Cargo.toml
[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
```

```rust
// ./macros/src/lib.rs
extern crate proc_macro;
use std::str::FromStr;
use proc_macro::TokenStream;

#[proc_macro]
pub fn include_tmp(_: TokenStream) -> TokenStream {
    let file = std::fs::read_to_string("./tmp.rs").unwrap();
    TokenStream::from_str(&file).unwrap()
}
```

```toml
[package]
name = "caller"
version = "0.1.0"
edition = "2021"

[dependencies]
macros = { path = "../macros" }
```

```rust
// ./caller/src/main.rs
macros::include_tmp!();
```

```rust
// ./tmp.rs
fn main() {
    println!("It works");
}
```
#### Using the expand macro code actions:
![image](https://user-images.githubusercontent.com/56133904/194526416-7e6e5e4b-f21a-48f5-ae7a-5011ef6d6589.png)
#### Running using `cargo`:
![image](https://user-images.githubusercontent.com/56133904/194526507-ddfc7136-075f-419d-a9eb-6373924ce38f.png)
