### ISSUE TITLE
failed when looking for declaration

### ISSUE THREAD

**Issue by zzwxh** [intellij-rust/intellij-rust#9553]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4932-222
* **Rust toolchain version:** stable-x86_64-pc-windows-msvc rustc 1.64.0 (a55dd71d5 2022-09-19)
* **IDE name and version:** CLion 2022.2.4 CL-222.4345.21
* **Operating system:** windows 11

## Problem description
![图片](https://user-images.githubusercontent.com/102860856/196117457-74d5d31d-5d35-4191-a77b-28ff2e624aac.png)

## Steps to reproduce
my main.rs:
```rust
use vulkano::{VulkanLibrary, instance::{Instance, InstanceCreateInfo}};
use vulkano::device::DeviceExtensions; //  < - no completion or highlighting ----------------------
use vulkano_win::VkSurfaceBuild;
use winit::{event_loop::EventLoop, window::WindowBuilder};

fn main() {
    let library = VulkanLibrary::new().unwrap();
    let required_extensions = vulkano_win::required_extensions(&library);
    let instance = Instance::new(
        library,
        InstanceCreateInfo {
            enabled_extensions : required_extensions,
            enumerate_portability : true,
            ..Default::default()
        }
    ).unwrap();
    let event_loop = EventLoop::new();
    let surface = WindowBuilder::new()
        .build_vk_surface(&event_loop, instance.clone())
        .unwrap();
    let device_extensions = DeviceExtensions{ // < - could not find declaration of the struct-------------
        ..DeviceExtensions::empty()
    };
}

```
my Cargo.toml:
```toml
[package]
name = "learn_vulkan_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.1"
vulkano = "0.31.1"
vulkano-win = "0.31.0"
winit = "0.27.4"
```
