### ISSUE TITLE
There is no inspection for feature name in Cargo.toml

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#9574]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4947-223-nightly
* **Rust toolchain version:** 1.66.0-nightly (06f049a35 2022-10-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.6646.99)
* **Operating system:** macOS 12.6
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description
There is no inspection for feature name in Cargo.toml

## Steps to reproduce

```toml
[dependencies]
bar = {path = "../bar", optional = true}

[features]
"dep:bar" = []
```
<img width="912" alt="Screenshot 2022-10-19 at 12 56 55" src="https://user-images.githubusercontent.com/1213122/196672654-c0ecf659-33a0-472e-b12a-e5713a324b7a.png">
