### ISSUE TITLE
Code completion for undeclared crates

### ISSUE THREAD

**Issue by rsalmei** [intellij-rust/intellij-rust#9634]
Please, why does the code completion system suggest methods from crates that **I don't use**??
I understand Rust does bring them as dependencies of dependencies of mine, but I do not declare them in my Cargo.toml, thus **I cannot use them**, so I think they should not be suggested at all. This makes the number of possible completions way bigger, but with **bogus** entries one cannot use, which makes the whole system more complex and cumbersome to use.

For example, I do not declare `itertools` in my Cargo dependencies, but its methods are still suggested:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/6652853/198470503-f136f63b-076a-43c7-8003-6f57eaf8c5af.png">
You can see the list is huge, and I dare to say MOST of the suggestions I don't declare and can't use...

If I incorrectly end up using one of these methods, Rust of course doesn't like it, the trait isn't in scope:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/6652853/198642645-ceaaa617-ae03-4ea8-9171-0b2dde74f030.png">
If I do try to use it, Rust says it is undeclared.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/6652853/198471142-d1d3bdac-fb62-4cf7-8383-982fca9e048f.png">

So please, would it be possible to not give suggestions of methods for crates I don't declare? Pretty please?

<details><summary>Project dependencies in Cargo.toml</summary>

```toml
[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["macros","sync","fs","rt-multi-thread"], default-features = false }
reqwest = { version= "0.11", features = ["json"] }
bytes = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = "1.0"
hex = "0.4"
toml = "0.5"
libchecksig = { version = "0.1", git = "https://github.com/cjdelisle/pkt-checksig", package = "libchecksig", branch = "main" }
blake2 = "0.9"
clap = { version = "3.2", features = ["derive"] }
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs", rev = "e40016bbc7546fb4d32340db074d3c66643cd5ca" }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.6"
lazy_static = "1.4"
strum = { version = "0.24", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "offline"] }
env_logger = "0.9"
log = "0.4"
heck = "0.4"
futures-util = "0.3"
```

</details>

## Environment

* **IntelliJ Rust plugin version:** 0.4.181.4965-222
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) aarch64-apple-darwin
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** macOS 13.0
* **Macro expansion:** enabled
