### ISSUE TITLE
Unresolved reference: `parse`

### ISSUE THREAD

**Issue by yiv** [intellij-rust/intellij-rust#9895]
## Environment

* **IntelliJ Rust plugin version: 0.4.184.5057-22
* **Rust toolchain version: 1.65.0
* **IDE name and version: IntelliJ IDEA 2022.3 (Ultimate Edition) Build #IU-223.7571.182, built on November 29, 2022 
* **Operating system: macOS Monterey ver 12.5.1

## Problem description
I am using Clap's derive feature to parse arguments, but method `parse` can not resolved

* This is the problem screenshot
![err](https://user-images.githubusercontent.com/16640312/207526659-fb645fbf-be54-415a-9cc3-d7cda6b89587.png)

* Also I have enabled `Expand macros`
![image](https://user-images.githubusercontent.com/16640312/207527062-f985ffa6-fbf9-412e-b7f3-7c67a4d5a124.png)

* `cargo run` & `cargo build` is ok
![image](https://user-images.githubusercontent.com/16640312/207528004-9855845f-0b2a-4db4-93b0-dd0fe8d0c3d9.png)

## Steps to reproduce

* cargo file
```toml
[package]
name = "tt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"]}
```

* main.rs
```rust
use std::path::PathBuf;
use clap::{Arg, Parser, command};


#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct DerivedConfig {
    #[arg(short, long)]
    derived: bool,
    #[arg(short, long, value_name = "FILE")]
    config: Option<PathBuf>,
}

fn use_derive(){

    let config = DerivedConfig::parse();
    println!("config  {:?}", config);
}

fn main() {
    use_derive();
}
```
